# Generated by Django 6.0 on 2025-12-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
